/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static project3.ViewJobs.myconobj;
import static project3.ViewJobs.myresobj;
import static project3.ViewJobs.mystatobj;
//import static project.userlogin.myobj;
//import static project.userlogin.myres;
//import static project.userlogin.mystat;
//import static project.userlogin.querypost;
//import static project.userlogin.sqlstat;

/**
 *
 * @author Dell
 */
public class functionality extends javax.swing.JFrame {
    private user u;
    

    /**
     * Creates new form functionality
     */
    public functionality() {
        initComponents();
    }
    
    public functionality(user u) {
       
        initComponents();
        this.u = u;
//        jTable1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        sendmsg = new javax.swing.JButton();
        jusermsg = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jmsg = new javax.swing.JLabel();
        jshow = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sendmsg.setText("Send Message");
        sendmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmsgActionPerformed(evt);
            }
        });

        jusermsg.setText("Enter Username");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jmsg.setText("Enter Message");

        jshow.setText("show sent messages");
        jshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton6.setText("show receive messages");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sendmsg)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jshow)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jusermsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jmsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(90, 90, 90)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jusermsg)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmsg)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(sendmsg)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jshow)
                            .addComponent(jButton6))
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(372, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addmessage(String send,String m,String rec) throws SQLException
    {
        System.out.println(rec + m);
        sqlstat = myconobj.prepareStatement("INSERT INTO IRTAZA.MESSAGE(SENDER,MESSAGE,RECEIVER) VALUES(?,?,?)");
        System.out.println(rec + m);
//        myres=mystat.executeQuery(querypost);        
        
//        System.out.println("IDDDD"+id);
        
        sqlstat.setString(1,send);
         sqlstat.setString(2,m);
         sqlstat.setString(3, rec);
//         sqlstat.setString(4,n);
         
         
         int a = sqlstat.executeUpdate();
    }
    
    

    
    
//    public void showposts()
//    {
//        try {
//            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//                model.setRowCount(0);
//               // System.out.println("entered function");
////                String qu="Delete from IRATZAFAYAZ.UNTITLED where id="+id;
//                 myres=mystat.executeQuery(querypost);
//            int j=0;
//            while(myres.next()){
//               int id=myres.getInt("ID");
//               String name= myres.getString("username");
//               int pid = myres.getInt("pid");
//               String post = myres.getString("post");
//                System.out.println(id+name+pid+post);
//                
//                
////                jTable1.setValueAt(id, j, 0);
////                jTable1.setValueAt(name, j, 1);
////                jTable1.setValueAt(pid, j, 2);
////                jTable1.setValueAt(post, j, 3);
//                
//                model.addRow(new Object[]{id,name,pid,post});
//                
//                
//                
//                j++;
//                
//            }
//        }
//                
// 
//             catch (SQLException ex) {
//                Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
//                System.out.println("error");
//            }
//    }
    
    
   
    
    
    
    private void sendmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmsgActionPerformed
        // TODO add your handling code here:
        
        String msg=jTextField3.getText();
        String usermsg=jTextField2.getText();
        System.out.println(msg + usermsg);
        if(msg.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Why do you want to send an empty message? eh?");
        }
        else if(usermsg.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Who do you want to send message? ghost? eh?");
        }
        else
        {
            u.addmessage(msg, usermsg);
            System.out.println(msg + usermsg);
            try {
                addmessage(u.getuserName(),msg,usermsg);
                System.out.println(msg + usermsg);
            } catch (SQLException ex) {
                Logger.getLogger(functionality.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(this, "Hey you just sent a message to "+ usermsg);
            
        }
        
        
        
        
    }//GEN-LAST:event_sendmsgActionPerformed

    private void jshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowActionPerformed
        // TODO add your handling code here:
        
        
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
                model.setRowCount(0);
        
        ArrayList<Message> msgs;
        try {
            msgs = u.showsend();
            String m,u;
        System.out.println(msgs.size());
        for(int i=0;i<msgs.size();i++)
        {
            m=msgs.get(i).getmessage();
            u=msgs.get(i).getusername();
            System.out.println(m);
            System.out.println(u);
            
            model.addRow(new Object[]{m,u});
            
        }
        } catch (SQLException ex) {
            Logger.getLogger(functionality.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jshowActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
    DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
                model.setRowCount(0);
        String n,u;
        try {        
            ArrayList<Message> msgs=user.showreceive();
            
            for(int i=0;i<msgs.size();i++)
            {
                n=msgs.get(i).getmessage();
                u=msgs.get(i).getusername();
                model.addRow(new Object[]{n,u});
                        
                        }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(functionality.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(functionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(functionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(functionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(functionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new functionality().setVisible(true);
            }
        });
    }
        public static Connection myconobj;
        public static Statement mystatobj=null;
        public static ResultSet myresobj=null;
        public static String query1=null;
        public static String queryusers="select * from users";
        public static PreparedStatement sqlstat=null;
    private user user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jmsg;
    private javax.swing.JButton jshow;
    private javax.swing.JLabel jusermsg;
    private javax.swing.JButton sendmsg;
    // End of variables declaration//GEN-END:variables
}
